version: '3.8'

services:
  job-postgres:
    container_name: job-postgres
    image: postgres:13
    ports:
      - "5920:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: staff_management
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  job-backend:
    container_name: job-backend
    build: ./Backend
    ports:
      - "3511:3511"
    depends_on:
      - job-postgres
    environment:
      - DB_HOST=job-postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=staff_management
      - PORT=3511

  hr-staff-ui:
    container_name: hr-staff-ui
    build: ./HR-staff
    ports:
      - "8128:80"
    depends_on:
      - job-backend

volumes:
  pgdata:


